### ISSUE TITLE
How to decode spectra.obj files?

### ISSUE THREAD

**Issue by X1nyuLu** [lyn1874/raman_spectra_matching_with_contrastive_learning#1]
Thanks for your sharing! It is a wonderful paper. However, i was wondering how to open the raw data of RRUFF which you upload at [this link](https://data.dtu.dk/articles/dataset/Datasets_for_replicating_the_paper_Raman_Spectrum_Matching_with_Contrastive_Representation_Learning_/20222331).
Actually ,i used scrpit as follow:
`with open('spectra.obj', 'r') as f: data = f.read()`
and i got this error `UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence
`

**Comment by lyn1874** [comment]
Hi, Thanks for your interest. : )

You are almost there. It is `import pickle; data = pickle.load(open("spectra_obj", "rb))`

**Comment by X1nyuLu** [comment]
It works. Thanks for your patience.
